// Copy this into your questions.js
const allQuestions = [
    { q: "Evaluate $\\lim_{x \\to -4} (x+1)^{1998}$", options: ["1", "0", "$\\infty$", "-1"], answer: 1 },
    { q: "Evaluate $\\lim_{x \\to 2} \\frac{x^3 - 8}{x - 2}$", options: ["4", "8", "12", "0"], answer: 2 },
    { q: "Evaluate $\\lim_{x \\to 0} \\frac{1 - \\cos x}{x}$", options: ["1/2", "Undefined", "1", "0"], answer: 3 },
    { q: "Evaluate $\\lim_{x \\to 2} \\frac{x^2 + 4}{x^4 - 8}$", options: ["2", "1", "0", "1/4"], answer: 1 },
    { q: "Evaluate $\\lim_{x \\to 2} \\frac{x^2 - 4}{x^2 + 4}$", options: ["4", "0", "1/2", "2"], answer: 1 },
    { q: "Find $\\lim_{x \\to \\infty} \\frac{4 - x^2}{x^2 - 1}$", options: ["1", "4", "-1", "0"], answer: 2 },
    { q: "Solve $\\lim_{x \\to 3} \\frac{x - 3}{x^2 - 2x - 3}$", options: ["0", "1/4", "3", "1/3"], answer: 1 },
    { q: "Find $\\lim_{x \\to 2} \\frac{x^3 - 8}{x^2 - 4}$", options: ["2", "6", "0", "3"], answer: 3 },
    { q: "Evaluate $\\lim_{x \\to \\infty} \\frac{4 - x^2}{4x^2 - x - 2}$", options: ["4", "1", "0", "-1/4"], answer: 3 },
    { q: "Calculate $\\lim_{x \\to 0} \\frac{\\sin 2x}{x}$", options: ["0", "1", "2", "1/2"], answer: 2 },
    { q: "Solve $\\lim_{x \\to 0} \\frac{\\sin 3x}{\\sin 4x}$", options: ["1", "0", "4/3", "3/4"], answer: 3 },
    { q: "Evaluate $\\lim_{x \\to 0} \\frac{\\tan \\pi x}{x}$", options: ["$\\pi$", "1", "0", "$\\pi/2$"], answer: 0 },
    { q: "If $f(x) = \\frac{x^2 - x}{2x}$ for $x \\neq 0$ and $f(0) = k$, find $k$ for continuity at $x=0$", options: ["1/2", "0", "1", "-1/2"], answer: 3 },
    { q: "Find $\\lim_{x \\to 0} \\frac{x}{|x|}$", options: ["1", "Does not exist", "0", "-1"], answer: 1 },
    { q: "Find $\\lim_{x \\to \\infty} x \\sin(1/x)$", options: ["0", "$\\infty$", "Undefined", "1"], answer: 3 },
    { q: "Find $\\lim_{x \\to 0} \\frac{\\sin x}{x^2 + 3x}$", options: ["1", "3", "1/3", "0"], answer: 2 },
    { q: "Find $\\lim_{x \\to \\pi} \\frac{\\sin(\\pi - x)}{\\pi - x}$", options: ["-1", "0", "Undefined", "1"], answer: 3 },
    { q: "Find $\\lim_{x \\to 0} x^2 \\sin(1/x)$", options: ["1", "Does not exist", "$\\infty$", "0"], answer: 3 },
    { q: "Find $\\lim_{x \\to 0} \\frac{e^x - 1}{x}$", options: ["e", "Undefined", "0", "1"], answer: 3 },
    { q: "Find $\\lim_{x \\to \\infty} \\frac{2x^2 + 1}{4 - x^2}$", options: ["2", "1/2", "0", "-2"], answer: 3 },
    { q: "Find $\\lim_{x \\to 0} \\frac{\\sin^2 x}{x^2}$", options: ["2", "1/2", "0", "1"], answer: 3 },
    { q: "Find $\\lim_{x \\to 0} \\frac{\\cos x - 1}{x^2}$", options: ["1/2", "1", "-1/2", "0"], answer: 2 },
    { q: "Find $\\lim_{x \\to 1} \\frac{x^2 - 1}{x - 1}$", options: ["1", "0", "Undefined", "2"], answer: 3 },
    { q: "Find $\\lim_{x \\to \\infty} \\frac{x^3}{e^x}$", options: ["$\\infty$", "1", "3", "0"], answer: 3 },
    { q: "Find $\\lim_{x \\to 0} \\frac{\\tan x - \\sin x}{x^3}$", options: ["1", "0", "-1/2", "1/2"], answer: 3 },
    { q: "Find $\\lim_{x \\to 2} \\frac{x^2 - 4}{x^4 - 16}$", options: ["1/4", "0", "4", "1/8"], answer: 3 },
    { q: "Find $\\lim_{x \\to 0} \\frac{\\sqrt{1+x}-1}{x}$", options: ["1", "0", "-1/2", "1/2"], answer: 3 },
    { q: "Find $\\lim_{x \\to 0} (1+x)^{1/x}$", options: ["1", "0", "$\\infty$", "e"], answer: 3 },
    { q: "Find $\\lim_{x \\to 1} \\frac{\\ln x}{x-1}$", options: ["0", "$\\infty$", "-1", "1"], answer: 3 },
    { q: "Find $\\lim_{x \\to 0} \\frac{\\sin 3x}{2x}$", options: ["2/3", "1", "0", "3/2"], answer: 3 },
  
         // Add these below your limits section in questions.js
    { q: "Differentiate $y = \\frac{4x^3+8}{2x^2+3}$ with respect to $x$ (2005 Neco)", options: ["$\\frac{8x^4+36x^2-32x}{(2x^2+3)^2}$", "$\\frac{2x^2+3}{12x^2}$", "0", "1"], answer: 0 },
    { q: "Find $dy/dx$ for $y = x / \\cos x$", options: ["$1+x \\sec x \\tan x$", "$\\sec x + x \\sec x \\tan x$", "$\\cos x + x \\sin x$", "1"], answer: 1 },
    { q: "Find $dy/dx$ for $y = (x+1)^{10}$", options: ["$10x^9$", "$9(x+1)^{10}$", "$(x+1)^9$", "$10(x+1)^9$"], answer: 3 },
    { q: "Find $dy/dx$ for $y = \\sqrt{2x+3}$", options: ["$2\\sqrt{2x+3}$", "$\\frac{1}{2\\sqrt{2x+3}}$", "$\\frac{1}{\\sqrt{2x+3}}$", "$\\sqrt{2x+3}$"], answer: 1 },
    { q: "Gradient of $y = \\frac{3x}{x+1}$ at $x=2$", options: ["3", "1", "1/3", "0"], answer: 2 },
    { q: "Differentiate $y = 500 \\csc x$", options: ["$-500 \\csc x \\cot x$", "$500 \\csc x \\cot x$", "$-500 \\sec x \\tan x$", "0"], answer: 0 },
    { q: "Find $dy/dx$ for $y=x^{12}+a+b+c+d+e$", options: ["$12x^{11}+a$", "0", "$12x^{12}$", "$12x^{11}$"], answer: 3 },
    { q: "Find $dy/dx$ for $y = \\frac{\\cos \\theta + \\sin \\theta}{\\sin \\theta}$", options: ["1", "$\\csc^2 \\theta$", "$-\\csc^2 \\theta$", "0"], answer: 2 },
    { q: "Find $dy/dx$ for $y = 2(\\frac{1-x^2}{1+x^2})$", options: ["$\\frac{-8x}{(1+x^2)^2}$", "1", "$\\frac{8x}{(1+x^2)^2}$", "0"], answer: 0 },
    { q: "Differentiate $f(x) = 2x(x^2+3)$", options: ["$2x^2+6$", "$6x^2+6$", "$6x^2+3$", "$2x^2+3$"], answer: 1 },
    { q: "Find $dy/dx$ for $y = (1+x)^2$", options: ["$1+x$", "$1+2x$", "$2+2x$", "$2(1+x)$"], answer: 2 },
    { q: "Differentiate $y = 3x^2 + 2/x$", options: ["$6x + 2/x^2$", "$6x - 2/x^2$", "$3x - 2/x^2$", "0"], answer: 1 },
    { q: "Find $dy/dx$ for $y = x \\sin x$", options: ["$\\sin x - x \\cos x$", "1", "$\\sin x + x \\cos x$", "$\\cos x + x \\sin x$"], answer: 2 },
    { q: "Differentiate $y = \\sin^2(5x)$", options: ["$2 \\sin 5x \\cos 5x$", "$5 \\sin 5x \\cos 5x$", "1", "$10 \\sin 5x \\cos 5x$"], answer: 3 },
    { q: "Find $dy/dx$ for $y = \\log_e(\\tan 2x)$", options: ["$\\tan 2x$", "$2 \\sec^2 2x / \\tan 2x$", "0", "$\\sec^2 2x / \\tan 2x$"], answer: 1 },
    { q: "Differentiate $y = (3x-1)^{1/3}$", options: ["$\\frac{1}{3(3x-1)^{2/3}}$", "0", "$\\frac{3}{(3x-1)^{2/3}}$", "$\\frac{1}{(3x-1)^{2/3}}$"], answer: 0 },
    { q: "Find $dy/dx$ for $y = e^{2x+3}$", options: ["$3e^{2x+3}$", "0", "$2e^{2x+3}$", "$e^{2x+3}$"], answer: 2 },
    { q: "Find $dy/dx$ for $y = \\sin(2x^3+3x-4)$", options: ["$(6x^2+3)\\sin(2x^3+3x-4)$", "0", "$\\cos(2x^3+3x-4)$", "$(6x^2+3)\\cos(2x^3+3x-4)$"], answer: 3 },
    { q: "Differentiate $y = x^3+x^2$", options: ["$x^2+2x$", "0", "$3x^2+x$", "$3x^2+2x$"], answer: 3 },
    { q: "Find $dy/dx$ for $y = \\cos(3x^2-2x)$", options: ["$(6x-2)\\sin(3x^2-2x)$", "0", "$-(6x-2)\\sin(3x^2-2x)$", "$-(6x-2)\\cos(3x^2-2x)$"], answer: 2 },
    { q: "Find $dy/dx$ for $y = (x^2+5)^4$", options: ["$4x(x^2+5)^3$", "0", "$8x(x^2+5)^4$", "$8x(x^2+5)^3$"], answer: 3 },
    { q: "Differentiate $y = 3\\sqrt{x^3}$", options: ["$9\\sqrt{x}$", "0", "$\\frac{3}{2}\\sqrt{x}$", "$\\frac{9}{2}\\sqrt{x}$"], answer: 3 },
    { q: "Find $d^2y/dx^2$ for $y = x^3-2x^2+4$", options: ["$6x+4$", "2", "$6x-4$", "$3x^2-4x$"], answer: 2 },
    { q: "Differentiate $y = \\sec x$", options: ["$-\\sec x \\tan x$", "1", "$\\sec^2 x$", "$\\sec x \\tan x$"], answer: 3 },
    { q: "Differentiate $y = \\cot x$", options: ["1", "$\\csc^2 x$", "$-\\csc^2 x$", "$-\\sec^2 x$"], answer: 2 },
    { q: "Find $dy/dx$ for $y = \\frac{2x-3}{x^2+5}$", options: ["1", "$\\frac{-2x^2+6x+10}{(x^2+5)^2}$", "$\\frac{2x^2-6x-10}{(x^2+5)^2}$", "0"], answer: 1 },
    { q: "Differentiate $y = x \\ln x$", options: ["$x$", "1", "$1+\\ln x$", "$\\ln x$"], answer: 2 },
    { q: "Find $dy/dx$ for $y = (2x+3)^5$", options: ["$2(2x+3)^4$", "0", "$5(2x+3)^4$", "$10(2x+3)^4$"], answer: 3 },
    { q: "Find $dy/dx$ for $y = \\frac{1}{x^2} - \\frac{1}{x}$", options: ["$2x^{-3}+x^{-2}$", "$2x^{-3}-x^{-2}$", "0", "$-2x^{-3}+x^{-2}$"], answer: 3 },
    { q: "Differentiate $y=3\\tan z / 117$", options: ["$\\frac{\\sec^2 z}{117}$", "$3\\sec^2 z / 117$", "$\\sec^2 z$", "0"], answer: 1 },
  
// Add these below your derivatives section in questions.js
    { q: "At turning points P and Q on a curve, the gradient $dy/dx$ is:", options: ["1", "-1", "undefined", "0"], answer: 3 },
    { q: "If $f''(x) > 0$, the function has a:", options: ["Maximum", "Inflection", "Discontinuity", "Minimum"], answer: 3 },
    { q: "Turning point of $f(x) = x^2-3x+2$ is at:", options: ["$x=1$", "$x=2$", "$x=3/2$", "$x=0$"], answer: 2 },
    { q: "Max value of $y = 1-2x-3x^2$ is:", options: ["1", "4/3", "0", "2/3"], answer: 1 },
    { q: "For $f(x) = x^3-6x^2+5$, turning points are at:", options: ["$x=0$ and $4$", "$x=2$ and $4$", "$x=0$ and $2$", "$x=-4$ and $0$"], answer: 0 },
    { q: "Gradient of $x^2-2xy-2y^2-2x=0$ at $(1, -4)$ is:", options: ["$4/7$", "$-4/7$", "$-2/7$", "$2/7$"], answer: 1 },
    { q: "If $V = \\frac{4}{3} \\pi r^3$, find $dV/dr$:", options: ["$4\\pi r^2$", "$8\\pi r$", "$4/3 \\pi r^2$", "0"], answer: 0 },
    { q: "Min value of $y = x^2-3x+2$ for real $x$:", options: ["$1/4$", "$1$", "-1/4", "0"], answer: 2 },
    { q: "For $f(x) = x^3-x$, minimum is at:", options: ["$x=0$", "$x=1$", "$x=-1/\\sqrt{3}$", "$x=1/\\sqrt{3}$"], answer: 3 },
    { q: "If $y^2+x^2-3xy=4$, find implicit $dy/dx$:", options: ["$(3y-2x)/(2y-3x)$", "0", "1", "$(2x-3y)/(3x-2y)$"], answer: 0 },
    { q: "Turning point of $y=x^2-2x-3$ is at:", options: ["$x=2$", "$x=0$", "$x=-1$", "$x=1$"], answer: 3 },
    { q: "Max value of $2+\\sin(\\theta+25^\\circ)$:", options: ["1", "2", "4", "3"], answer: 3 },
    { q: "Min value of $f(x) = x^2+3x+7$:", options: ["7", "19/4", "3/2", "0"], answer: 1 },
    { q: "Max value of $x^3-12x+11$ is at:", options: ["$x=1$", "$x=0$", "$x=-2$", "$x=2$"], answer: 2 },
    { q: "Turning points of $y = 2x^3-6x^2-18x+3$:", options: ["$(-1, -13)$ and $(3, 51)$", "$(-1, 13)$ and $(3, -51)$", "$(1, 13)$ and $(-3, -51)$", "0"], answer: 1 },
    { q: "Gradient of $x^2-2xy-2y^2-2x=0$ at $(1, -4)$ is:", options: ["$-2/7$", "$2/7$", "$4/7$", "$-4/7$"], answer: 3 },
    { q: "Find derivative of $x^2+y^2=25$ at $(3, 4)$:", options: ["$4/3$", "$-3/4$", "$-4/3$", "$3/4$"], answer: 1 },
    { q: "If $y = x^3$, at $x=0$ the point is:", options: ["Maximum", "Minimum", "Inflection", "Discontinuity"], answer: 2 },
    { q: "Turning point of $f(x) = -3x^2+3x+2$:", options: ["$(1/2, 1/4)$", "$(-1/2, 11/4)$", "$(-1/2, 1/4)$", "$(1/2, 11/4)$"], answer: 3 },
    { q: "For $3x^2+2y^2+xy+x-7=0$, implicit derivative:", options: ["$1$", "$-(6x+y+1)/(4y+x)$", "$(6x+y+1)/(4y+x)$", "0"], answer: 1 },
    { q: "Find $dy/dx$ for $4x^4+y^3=12x^2y$:", options: ["1", "$(16x^3-12x^2y)/(3y^2-12x^2)$", "$(12x^2y-16x^3)/(3y^2-12x^2)$", "0"], answer: 2 },
    { q: "Min value of $y = x^3-7x^2+15x$:", options: ["$x=5/3$", "$x=3$", "$x=-5/3$", "$x=5/3$ or $3$"], answer: 1 },
    { q: "For $y = 4t^2-40t+300$, minimum is at:", options: ["$t=20$", "$t=10$", "$t=5$", "$t=0$"], answer: 2 },
    { q: "For $x^2-6x+3$, gradient is zero at:", options: ["$x=-3$", "$x=0$", "$x=6$", "$x=3$"], answer: 3 },
    { q: "Max value of $x^3-12x+11$ is at:", options: ["$x=0$", "$x=1$", "$x=2$", "$x=-2$"], answer: 3 },
    { q: "Gradient of $2x^2-5x+6$ at $x=1$:", options: ["2", "1", "0", "-1"], answer: 3 },
    { q: "Max value of $f(x) = 2x^3-x^2-4x+4$:", options: ["$x=0$", "$x=-2/3$", "$x=1$", "$x=2/3$"], answer: 1 },
    { q: "Min value of $y=x^2-2x-3$:", options: ["$x=2$", "$x=-1$", "$x=0$", "$x=1$"], answer: 3 },
    { q: "If $y = x^2-3x+2$, find min point:", options: ["$(1.5, -0.25)$", "$(1.5, 0.25)$", "$(-1.5, -0.25)$", "$(0, 2)$"], answer: 0 },
    { q: "For $f(x)=x^3-x$, min value is at:", options: ["$x=1$", "$x=0$", "$x=1/\\sqrt{3}$", "$x=-1/\\sqrt{3}$"], answer: 2 },
  // Add these to complete your questions.js file
    { q: "$f: x \\to x^2+6$, domain if range is $\{6, 7, 10, 15\}$:", options: ["$\{5, 6, 8, 12\}$", "$\{-1, 0, 1, 2\}$", "$\{0, 1, 2, 3\}$", "$\{-2, -1, 0, 1\}$"], answer: 2 },
    { q: "Given $f(x)=3x-2$, find $f^{-1}(x)$:", options: ["$3x+2$", "x+2", "$(x-2)/3$", "$(x+2)/3$"], answer: 3 },
    { q: "Range of $f(x)=x^2-x-2$ for $W=\{-1, 0, 2, 5, 11\}$:", options: ["$\{-1, 0, 2, 5\}$", "$\{0, 18\}$", "$\{-2, 0, 18\}$", "$\{-2, 0, 18, 108\}$"], answer: 3 },
    { q: "$f: x \\to x+1$ is what mapping:", options: ["Constant", "Many-to-one", "One-to-one", "Onto"], answer: 2 },
    { q: "If $f(x)=2x+1$ and $g(x)=x^2-2$, find $g \\circ f$:", options: ["$x^2+2x-1$", "$4x^2+4x-1$", "$4x^2-4x+1$", "0"], answer: 1 },
    { q: "Domain of $f(x) = \\frac{x}{3-x}$:", options: ["$x > 3$", "All Real", "$x \\neq 0$", "$x \\neq 3$"], answer: 3 },
    { q: "$f(x)=x^2-1$, what is $f(0)$?:", options: ["1", "0", "2", "-1"], answer: 3 },
    { q: "$f: A \\to B$, a mapping is onto if:", options: ["Range = Codomain", "Bijective", "Injective", "Range $\\subset$ Codomain"], answer: 0 },
    { q: "If $f(x) = x+3$, find $f^{-1}(-1)$:", options: ["4", "1", "-4", "2"], answer: 2 },
    { q: "$f(x) = 2x-3$, find $f(2)$:", options: ["4", "1", "7", "0"], answer: 1 },
    { q: "Mapping $f: S \\to T$ is a function if:", options: ["Mapping is empty", "Each domain has many images", "Each domain has one image", "None"], answer: 2 },
    { q: "Domain of area $\\pi r^2$:", options: ["$r \\geq 0$", "All Real", "$r < 0$", "$r > 0$"], answer: 0 },
    { q: "Inverse of $f(x) = e^x$:", options: ["$x$", "$\\log_{10} x$", "$1/e^x$", "$\\ln x$"], answer: 3 },
    { q: "Find $g(x+1)-g(x)$ if $g(x)=x^2+3x+4$:", options: ["$2x+3$", "$2x+4$", "$x+4$", "0"], answer: 1 },
    { q: "If $f(x)=1/(x-1)$, find $f(1-x)$:", options: ["$1/(x-1)$", "$1/x$", "$-1/x$", "0"], answer: 2 },
    { q: "If $f(x)=x/(x-2)$, find $f^{-1}(x)$:", options: ["$x/(x+1)$", "$2x/(x+1)$", "$2x/(x-1)$", "0"], answer: 1 },
    { q: "If $f(x)=x^3+5$, find $f^{-1}(x)$:", options: ["$x-5$", "$\\sqrt[3]{x+5}$", "$\\sqrt[3]{x-5}$", "0"], answer: 2 },
    { q: "Find $g(f(x))$ if $f(x)=x^2, g(x)=2x-1$:", options: ["$x^2-1$", "$2(x-1)^2$", "$2x^2-1$", "0"], answer: 2 },
    { q: "Mapping $f(x)=c$ is:", options: ["Linear", "Identity", "Constant", "Quadratic"], answer: 2 },
    { q: "Range of $f(x)=x^2-2$ for $\\{-2, -1, 0, 1\\}$:", options: ["$\{1, 2\}$", "$\{-2, -1, 0\}$", "$\{-2, -1, 2\}$", "0"], answer: 2 },
    { q: "Find $f(x)$ if $f(x+1) = x^2+2x+3$:", options: ["$x^2+3$", "$x^2+2$", "$x^2+1$", "0"], answer: 1 },
    { q: "Mapping $f(x)=x$ is:", options: ["Quadratic", "Linear", "Constant", "Identity"], answer: 3 },
    { q: "If $f(x) = 1/(2-x)$, find $f^{-1}(-1/2)$:", options: ["2", "-2", "0", "4"], answer: 3 },
    { q: "If $g(x)=x^2+2x+1$, find $g(1)$:", options: ["1", "4", "2", "0"], answer: 1 },
    { q: "Find $f(2)$ if $f(x-4) = x^2+2x+3$:", options: ["27", "3", "51", "0"], answer: 0 },
    { q: "If $f(x) = 2x^2+5x+2$, find $f(1)$:", options: ["2", "5", "7", "9"], answer: 3 },
    { q: "Mapping where range $\\subset$ codomain:", options: ["Injective", "Bijective", "Onto", "Into"], answer: 3 },
    { q: "Composition $f(g(x))$ is:", options: ["$fg$", "$f+g$", "$g \\circ f$", "$f \\circ g$"], answer: 3 },
    { q: "If $f(x) = x^2-1$, $f(f(2))$ is:", options: ["5", "3", "8", "0"], answer: 0 },
    { q: "Find $f(x)$ for linear $f(x)$ where $f'(x)=-3, f(1)=4$:", options: ["$-3x-7$", "$3x+4$", "$-3x+7$", "0"], answer: 2 }
];
                                                        
      
